distance-to-count: 100

red-blocks:
  - "CRIMSON_NYLIUM"
  - "WARPED_NYLIUM"
  - "NETHER_GOLD_ORE"
  - "CRIMSON_STEM"
  - "CRIMSON_HYPHAE"
  - "RED_WOOL"
  - "NETHERRACK"
  - "REDSTONE_ORE"
  - "BOOKSHELF"
  - "NETHER_QUARTZ_ORE"
  - "RED_TERRACOTTA"
  - "RED_STAINED_GLASS"
  - "RED_NETHER_BRICKS"
  - "NETHER_WART_BLOCK"
  - "RED_CONCRETE"
  - "RED_CONCRETE_POWDER"
  - "FIRE_CORAL_BLOCK"
  - "RED_NETHER_BRICK_STAIRS"
  - "RED_NETHER_BRICK_SLAB"
  - "POPPY"
  - "RED_TULIP"
  - "RED_MUSHROOM"
  - "CRIMSON_FUNGUS"
  - "CRIMSON_ROOTS"
  - "WEEPING_VINES"
  - "RED_MUSHROOM_BLOCKS"
  - "NETHER_WART"
  - "RED_NETHER_BRICK_WALL"
  - "RED_CARPET"
  - "ROSE_BUSH"
  - "RED_STAINED_GLASS_PANE"
  - "RED_SHULKER_BOX"
  - "RED_GLAZED_TERRACOTTA"
  - "BLACK_GLAZED_TERRACOTTA"
  - "FIRE_CORAL"
  - "FIRE_CORAL_FAN"
  - "RED_BED"
  - "RED_BANNER"
  - "FLETCHING_TABLE"
  - "TNT"
  - "REDSTONE_TORCH"
  - "REDSTONE_BLOCK"
  - "REPEATER"
  - "COMPARATOR"
  - "REDSTONE"
  - "LECTERN"
  - "TARGET"
  - "DETECTOR_RAIL"
  - "POWERED_RAIL"
  - "ACTIVATOR_RAIL"
  - "RED_DYE"
  - "CAKE"
  - "SWEET_BERRIES"
  - "BEETROOT"